import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { CodeGraphManager } from './index';

export interface DeepSyncReportOptions {
  repoPath: string;
  filesAnalyzed: number;
  symbolCount: number;
  nodeCount: number;
  edgeCount: number;
  docsIngested: number;
  commitsAnalyzed: number;
  memoryCount: number;
  gitBranch?: string;
  languageBreakdown?: Record<string, number>;
  docFiles?: Array<{ path: string; sizeKB: number }>;
  hotFiles?: Array<{ path: string; changes: number }>;
  recentFocusAreas?: string[];
  durationMs: number;
}

/**
 * Generate a DEEPSYNC.md report summarising the deep sync results.
 */
export async function generateDeepSyncReport(options: DeepSyncReportOptions): Promise<string> {
  const graphManager = new CodeGraphManager(options.repoPath);
  const projectName = path.basename(options.repoPath);
  const syncedAt = new Date().toISOString();

  // Language breakdown table
  let langTable = '| Language | Files |\n|----------|-------|\n';
  if (options.languageBreakdown) {
    const sorted = Object.entries(options.languageBreakdown).sort((a, b) => b[1] - a[1]);
    const total = sorted.reduce((s, [, c]) => s + c, 0);
    for (const [lang, count] of sorted) {
      const pct = total > 0 ? ((count / total) * 100).toFixed(0) : '0';
      langTable += `| ${lang} | ${count} (${pct}%) |\n`;
    }
  } else {
    langTable += '| — | No data |\n';
  }

  // God-nodes section
  let godNodesSection = '';
  try {
    const godNodes = await graphManager.getGodNodes(10);
    if (godNodes.length > 0) {
      const rows = godNodes
        .map((gn, i) => `| ${i + 1} | \`${gn.path}\` | ${gn.degree} | ${gn.inDegree} | ${gn.outDegree} |`)
        .join('\n');
      godNodesSection = `### 🔗 God-Nodes (Most Connected Files)

| Rank | File | Degree | In | Out |
|------|------|--------|----|-----|
${rows}
`;
    }
  } catch {}

  // Communities section
  let communitiesSection = '';
  try {
    const communities = await graphManager.detectCommunities();
    if (communities.length > 0) {
      const topCommunities = communities.slice(0, 8);
      const rows = topCommunities
        .map((c) => {
          const preview = c.files
            .slice(0, 4)
            .map((f) => `\`${f}\``)
            .join(', ');
          const more = c.size > 4 ? ` +${c.size - 4} more` : '';
          return `| ${c.id} | ${c.size} | ${preview}${more} |`;
        })
        .join('\n');
      communitiesSection = `### 🏘️ Code Communities

Total: **${communities.length}** communities across **${communities.reduce((s, c) => s + c.size, 0)}** files.

| ID | Size | Files |
|----|------|-------|
${rows}
`;
    }
  } catch {}

  // Documentation index
  let docsSection = '';
  if (options.docFiles && options.docFiles.length > 0) {
    const rows = options.docFiles
      .slice(0, 20)
      .map((d) => `| \`${d.path}\` | ${d.sizeKB.toFixed(1)} KB |`)
      .join('\n');
    docsSection = `### 📄 Documentation Index

| File | Size |
|------|------|
${rows}
`;
  }

  // Git intelligence
  let gitSection = '';
  if (options.gitBranch || (options.hotFiles && options.hotFiles.length > 0)) {
    gitSection = `### 🔀 Git Intelligence

`;
    if (options.gitBranch) {
      gitSection += `- **Active Branch:** \`${options.gitBranch}\`\n`;
    }
    gitSection += `- **Commits Analyzed:** ${options.commitsAnalyzed}\n`;

    if (options.hotFiles && options.hotFiles.length > 0) {
      gitSection += `\n**Hot Files** (most changed recently):\n`;
      for (const hf of options.hotFiles.slice(0, 10)) {
        gitSection += `- \`${hf.path}\` — ${hf.changes} changes\n`;
      }
    }

    if (options.recentFocusAreas && options.recentFocusAreas.length > 0) {
      gitSection += `\n**Recent Focus Areas:** ${options.recentFocusAreas.join(', ')}\n`;
    }
  }

  const durationSec = (options.durationMs / 1000).toFixed(1);

  const report = `# 🧠 DeepSync Report — ${projectName}

> Auto-generated by ContextHub DeepSync. Do not edit manually.
> Last synced: ${syncedAt} | Duration: ${durationSec}s

---

## 📊 Overview

| Metric | Count |
|--------|-------|
| Files Analyzed | ${options.filesAnalyzed} |
| Symbols Indexed | ${options.symbolCount} |
| Graph Nodes | ${options.nodeCount} |
| Graph Edges | ${options.edgeCount} |
| Docs Ingested | ${options.docsIngested} |
| Commits Analyzed | ${options.commitsAnalyzed} |
| Total Memories | ${options.memoryCount} |

## 🗂️ Languages

${langTable}

## 🏗️ Architecture

${godNodesSection || '> No high-connectivity files detected.\n'}
${communitiesSection || '> No communities detected.\n'}

${docsSection}

${gitSection}

---

## 🔄 Auto-Sync

DeepSync auto-updates the knowledge graph on every \`ensure_session\` call.
Changed files are detected via git and incrementally patched — no manual re-scan needed.

---

*Generated by [ContextHub DeepSync](https://github.com/iMayuuR/contexthub) — One scan. Total recall. Forever in context.*
`;

  return report;
}

/**
 * Write the DeepSync report to .contexthub/DEEPSYNC.md
 */
export async function writeDeepSyncReport(options: DeepSyncReportOptions): Promise<string> {
  const report = await generateDeepSyncReport(options);
  const outputPath = path.join(options.repoPath, '.contexthub', 'DEEPSYNC.md');

  // Ensure .contexthub exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Atomic write
  const tmpPath = outputPath + `.tmp.${crypto.randomBytes(4).toString('hex')}`;
  try {
    fs.writeFileSync(tmpPath, report, { mode: 0o600 });
    fs.renameSync(tmpPath, outputPath);
  } catch (e) {
    try {
      fs.unlinkSync(tmpPath);
    } catch {}
    throw e;
  }

  return outputPath;
}
