import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { CodeGraphManager } from './index';

export interface GraphReportOptions {
  repoPath: string;
  memoryCount?: number;
  gitBranch?: string;
  lastPatch?: string;
}

/**
 * Generate a GRAPH_REPORT.md summarising the knowledge graph state.
 * Called from watch batches, update_knowledge_graph, and the CLI.
 */
export async function generateGraphReport(options: GraphReportOptions): Promise<string> {
  const graphManager = new CodeGraphManager(options.repoPath);

  let graph;
  try {
    graph = await graphManager.loadGraph();
  } catch {
    return '# ContextHub Graph Report\n\n> No code graph available. Run `contexthub watch` or `contexthub setup` first.\n';
  }

  // Stats
  const fileNodes = graph.nodes.filter(n => n.kind === 'file');
  const symbolNodes = graph.nodes.filter(n => n.kind === 'symbol');
  const importEdges = graph.edges.filter(e => e.kind === 'imports');
  const containsEdges = graph.edges.filter(e => e.kind === 'contains');

  // Languages
  const langCounts: Record<string, number> = {};
  for (const node of fileNodes) {
    const lang = node.lang || 'unknown';
    langCounts[lang] = (langCounts[lang] || 0) + 1;
  }
  const langTable = Object.entries(langCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([lang, count]) => `| ${lang} | ${count} |`)
    .join('\n');

  // God-nodes (top 10)
  let godNodesSection = '';
  try {
    const godNodes = await graphManager.getGodNodes(10);
    if (godNodes.length > 0) {
      const rows = godNodes.map((gn, i) =>
        `| ${i + 1} | \`${gn.path}\` | ${gn.degree} | ${gn.inDegree} | ${gn.outDegree} |`
      ).join('\n');
      godNodesSection = `## God-nodes (Top 10 Most Connected Files)

| Rank | File | Degree | In | Out |
|------|------|--------|----|-----|
${rows}
`;
    } else {
      godNodesSection = '## God-nodes\n\nNo high-connectivity files detected.\n';
    }
  } catch {
    godNodesSection = '## God-nodes\n\nUnable to compute god-nodes.\n';
  }

  // Communities
  let communitiesSection = '';
  try {
    const communities = await graphManager.detectCommunities();
    if (communities.length > 0) {
      const topCommunities = communities.slice(0, 10);
      const rows = topCommunities.map(c => {
        const preview = c.files.slice(0, 5).map(f => `\`${f}\``).join(', ');
        const more = c.size > 5 ? ` (+${c.size - 5} more)` : '';
        return `| ${c.id} | ${c.size} | ${preview}${more} |`;
      }).join('\n');
      communitiesSection = `## Communities (Connected Components)

Total: **${communities.length}** communities across **${communities.reduce((s, c) => s + c.size, 0)}** files.

| ID | Size | Files (preview) |
|----|------|-----------------|
${rows}
`;
    } else {
      communitiesSection = '## Communities\n\nNo communities detected.\n';
    }
  } catch {
    communitiesSection = '## Communities\n\nUnable to compute communities.\n';
  }

  const updatedAt = graph.updatedAt ? new Date(graph.updatedAt).toISOString() : 'unknown';

  const report = `# ContextHub Graph Report

> Auto-generated by ContextHub. Do not edit manually.
> Last updated: ${updatedAt}

## Overview

| Metric | Count |
|--------|-------|
| Files | ${fileNodes.length} |
| Symbols | ${symbolNodes.length} |
| Total Nodes | ${graph.nodes.length} |
| Import Edges | ${importEdges.length} |
| Contains Edges | ${containsEdges.length} |
| Total Edges | ${graph.edges.length} |
| Graph Version | ${graph.version} |
${options.memoryCount !== undefined ? `| Memories | ${options.memoryCount} |\n` : ''}${options.gitBranch ? `| Git Branch | ${options.gitBranch} |\n` : ''}${options.lastPatch ? `| Last Patch | ${options.lastPatch} |\n` : ''}
## Languages

| Language | Files |
|----------|-------|
${langTable}

${godNodesSection}
${communitiesSection}
---

*Generated by [ContextHub](https://github.com/iMayuuR/contexthub)*
`;

  return report;
}

/**
 * Write the graph report to .contexthub/GRAPH_REPORT.md
 */
export async function writeGraphReport(options: GraphReportOptions): Promise<string> {
  const report = await generateGraphReport(options);
  const outputPath = path.join(options.repoPath, '.contexthub', 'GRAPH_REPORT.md');

  // Ensure .contexthub exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Atomic write
  const tmpPath = outputPath + `.tmp.${crypto.randomBytes(4).toString('hex')}`;
  try {
    fs.writeFileSync(tmpPath, report, { mode: 0o600 });
    fs.renameSync(tmpPath, outputPath);
  } catch (e) {
    try { fs.unlinkSync(tmpPath); } catch {}
    throw e;
  }

  return outputPath;
}
